LOCAL_AUTHORITIES = [
    ("Blaenau Gwent", "Blaenau Gwent"),
    ("Bridgend", "Bridgend"),
    ("Caerphilly", "Caerphilly"),
    ("Cardiff", "Cardiff"),
    ("Carmarthenshire", "Carmarthenshire"),
    ("Ceredigion", "Ceredigion"),
    ("Conwy", "Conwy"),
    ("Denbighshire", "Denbighshire"),
    ("Flintshire", "Flintshire"),
    ("Gwynedd", "Gwynedd"),
    ("Isle of Anglesey", "Isle of Anglesey"),
    ("Merthyr Tydfil", "Merthyr Tydfil"),
    ("Monmouthshire", "Monmouthshire"),
    ("Neath Port Talbot", "Neath Port Talbot"),
    ("Newport", "Newport"),
    ("Pembrokeshire", "Pembrokeshire"),
    ("Powys", "Powys"),
    ("Rhondda Cynon Taf", "Rhondda Cynon Taf"),
    ("Swansea", "Swansea"),
    ("Torfaen", "Torfaen"),
    ("Vale of Glamorgan", "Vale of Glamorgan"),
    ("Wrexham", "Wrexham"),
]
